name: timothy

services:
  dunder_mifflin:
    container_name: dunder-mifflin
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: michael_scott
      POSTGRES_PASSWORD: thatswhatshesaid
  paper_company:
    container_name: michael-scott-paper-company
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: michael_scott
      POSTGRES_PASSWORD: thatswhatshesaid!
