name: timothy

services:
  michael_scott:
    container_name: michael-scott
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: michael_scott
      POSTGRES_PASSWORD: thatswhatshesaid
  jim_halpert:
    container_name: jim-halpert
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: jim_halpert
      POSTGRES_PASSWORD: bearseatbeetsbearbeetsbattlestargalactica
